# Generated by Django 3.0 on 2020-01-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribes',
            new_name='Subscriber',
        ),
    ]
